apiVersion: v1
items:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: pacman
      app.kubernetes.io/component: pacman
      app.kubernetes.io/instance: pacman
    name: nodejs-8
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations:
        openshift.io/imported-from: registry.access.redhat.com/ubi7/nodejs-8:latest
      from:
        kind: DockerImage
        name: registry.access.redhat.com/ubi7/nodejs-8:latest
      importPolicy: {}
      name: latest
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: pacman
      app.kubernetes.io/component: pacman
      app.kubernetes.io/instance: pacman
    name: pacman
  spec:
    lookupPolicy:
      local: false
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: pacman
      app.kubernetes.io/component: pacman
      app.kubernetes.io/instance: pacman
    name: pacman
  spec:
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: pacman:latest
    postCommit: {}
    resources: {}
    source:
      git:
        uri: https://github.com/cooktheryan/pacman.git
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: nodejs-8:latest
      type: Source
    triggers:
    - github:
        secret: EfEKdK3c99xP1A5ZjFR0
      type: GitHub
    - generic:
        secret: pVSwjovsCrypTgmfuhxT
      type: Generic
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: pacman
      app.kubernetes.io/component: pacman
      app.kubernetes.io/instance: pacman
    name: pacman
  spec:
    replicas: 1
    selector:
      deploymentconfig: pacman
    strategy:
      resources: {}
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          deploymentconfig: pacman
      spec:
        containers:
        - image: pacman:latest
          name: pacman
          ports:
          - containerPort: 8080
            protocol: TCP
          resources: {}
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - pacman
        from:
          kind: ImageStreamTag
          name: pacman:latest
      type: ImageChange
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: pacman
      app.kubernetes.io/component: pacman
      app.kubernetes.io/instance: pacman
    name: pacman
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      deploymentconfig: pacman
kind: List
metadata: {}
