bases:
- ../../base
patchesStrategicMerge:
- github-secret.yaml 
patchesJson6902:
  - target:
      version: v1
      group: config.openshift.io
      kind: OAuth
      name: cluster
    path: github-auth.yaml
  - target:
      version: v1
      kind: Secret 
      namespace: openshift-authentication 
      name: v4-0-config-user-idp-0-client-secret
    path: idp-secret.yaml
