apiVersion: v1
data:
  index.html: "The letter of the day is <img src=\"https://www.pngfind.com/pngs/m/7-76720_freeuse-clipart-letters-of-the-alphabet-free-gold.png\">
    \n"
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: index-map
  selfLink: /api/v1/namespaces/simple-app/configmaps/index-map
