apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pacman
  namespace: game-testing
subjects:
- kind: ServiceAccount 
  name: pacman
  namespace: game-testing
roleRef:
  kind: ClusterRole
  name: pacman-testing
  apiGroup: rbac.authorization.k8s.io
